#!/usr/bin/env bash

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 0-main.c 0-binary_tree_node.c -o 0-node ; ./0-node
echo "0===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 1-main.c 1-binary_tree_insert_left.c 0-binary_tree_node.c -o 1-left ; ./1-left
echo "1===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 2-main.c 2-binary_tree_insert_right.c 0-binary_tree_node.c -o 2-right ; ./2-right
echo "2===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 3-main.c 3-binary_tree_delete.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 3-del ; valgrind ./3-del
echo "3===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 4-binary_tree_is_leaf.c 4-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 4-leaf ; ./4-leaf
echo "4===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 5-binary_tree_is_root.c 5-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 5-root ; ./5-root
echo "5===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 6-main.c 6-binary_tree_preorder.c 0-binary_tree_node.c -o 6-pre ; ./6-pre
echo "6===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 7-main.c 7-binary_tree_inorder.c 0-binary_tree_node.c -o 7-in ; ./7-in
echo "7===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 8-main.c 8-binary_tree_postorder.c 0-binary_tree_node.c -o 8-post ; ./8-post
echo "8===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 9-binary_tree_height.c 9-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 9-height; ./9-height
echo "9===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 10-binary_tree_depth.c 10-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 10-depth; ./10-depth
echo "10===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 11-binary_tree_size.c 11-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 11-size; ./11-size
echo "11===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 12-binary_tree_leaves.c 12-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 12-leaves; ./12-leaves
echo "12===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 13-binary_tree_nodes.c 13-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 13-nodes; ./13-nodes
echo "13===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 14-binary_tree_balance.c 14-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c 1-binary_tree_insert_left.c -o 14-balance ; ./14-balance
echo "14===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 15-binary_tree_is_full.c 15-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 15-full; ./15-full
echo "15===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 16-binary_tree_is_perfect.c 16-main.c 0-binary_tree_node.c 2-binary_tree_insert_right.c -o 16-perfect ; ./16-perfect
echo "16===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 17-main.c 17-binary_tree_sibling.c 0-binary_tree_node.c -o 17-sibling ; ./17-sibling
echo "17===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 18-main.c 18-binary_tree_uncle.c 0-binary_tree_node.c -o 18-uncle ; ./18-uncle
echo "18===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 100-main.c 100-binary_trees_ancestor.c 0-binary_tree_node.c -o 100-ancestor ; ./100-ancestor
echo "19===================="; echo "====================";


echo "20===================="; echo "====================";

echo "21===================="; echo "====================";

echo "22===================="; echo "====================";

echo "23===================="; echo "====================";


gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 110-main.c 110-binary_tree_is_bst.c 0-binary_tree_node.c -o 110-is_bst; ./110-is_bst
echo "24===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 111-bst_insert.c 111-main.c 0-binary_tree_node.c -o 111-bst_insert ; ./111-bst_insert
echo "25===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 112-array_to_bst.c 112-main.c 111-bst_insert.c 0-binary_tree_node.c -o 112-bst_array ; ./112-bst_array
echo "26===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 113-bst_search.c 113-main.c 112-array_to_bst.c 111-bst_insert.c 0-binary_tree_node.c -o 113-bst_search ; ./113-bst_search
echo "27===================="; echo "====================";

gcc -g -Wall -Wextra -Werror -pedantic binary_tree_print.c 114-bst_remove.c 114-main.c 112-array_to_bst.c 111-bst_insert.c 0-binary_tree_node.c 3-binary_tree_delete.c -o 114-bst_rm ; ./114-bst_rm
echo "28===================="; echo "====================";


echo "41===================="; echo "====================";
